package my.study.planner;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;

public class EverydayActivity extends AppCompatActivity {

    Button everyday;
    Button everyWeek;
    Button everyMonth;
    LinearLayout ll;
    Button monday;
    Button tuesday;
    Button wednesday;
    Button thursday;
    Button friday;
    Button saturday;
    Button sunday;
    LinearLayout days;
    Button one;
    Button two;
    Button three;
    Button four;
    Button five;
    Button six;
    Button seven;
    Button eight;
    Button nine;
    Button ten;
    Button eleven;
    Button twelve;
    Button thirteen;
    Button fourteen;
    Button fifteen;
    Button sixteen;
    Button seventeen;
    Button eighteen;
    Button nineteen;
    Button twenty;
    Button twentyone;
    Button twentytwo;
    Button twentythree;
    Button twentyfour;
    Button twentyfive;
    Button twentysix;
    Button twentyseven;
    Button twentyeight;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_everyday);
        everyday = findViewById(R.id.everyday);
        everyWeek = findViewById(R.id.everyweek);
        everyMonth = findViewById(R.id.everymonth);
        ll = findViewById(R.id.week);
        monday = findViewById(R.id.monday);
        tuesday = findViewById(R.id.tuesday);
        wednesday = findViewById(R.id.wednesday);
        thursday = findViewById(R.id.thursday);
        friday = findViewById(R.id.friday);
        saturday = findViewById(R.id.saturday);
        sunday = findViewById(R.id.sunday);
        days = findViewById(R.id.days);
        one = findViewById(R.id.one);
        two = findViewById(R.id.two);
        three = findViewById(R.id.three);
        four = findViewById(R.id.four);
        five = findViewById(R.id.five);
        six = findViewById(R.id.six);
        seven = findViewById(R.id.seven);
        eight = findViewById(R.id.eight);
        nine = findViewById(R.id.nine);
        ten = findViewById(R.id.ten);
        eleven = findViewById(R.id.eleven);
        twelve = findViewById(R.id.tweleve);
        thirteen = findViewById(R.id.thirteen);
        fourteen = findViewById(R.id.fourteen);
        fifteen = findViewById(R.id.fifteen);
        sixteen = findViewById(R.id.sixteen);
        seventeen = findViewById(R.id.seventeen);
        eighteen = findViewById(R.id.eighteen);
        nineteen = findViewById(R.id.nineteen);
        twenty = findViewById(R.id.twenty);
        twentyone = findViewById(R.id.twentyone);
        twentytwo = findViewById(R.id.twentytwo);
        twentythree = findViewById(R.id.twentythree);
        twentyfour = findViewById(R.id.twentyfour);
        twentyfive = findViewById(R.id.twentyfive);
        twentysix = findViewById(R.id.twentysix);
        twentyseven = findViewById(R.id.twentyseven);
        twentyeight = findViewById(R.id.twentyeight);
    }
    public void every(View v){
        switch (v.getId()) {
            case R.id.everyday:
                ll.setVisibility(View.GONE);
                days.setVisibility(View.GONE);
                everyday.setBackgroundResource(R.drawable.round_pastel_yellow);
                everyWeek.setBackgroundResource(R.drawable.grey_round_button);
                everyMonth.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.everyweek:
                ll.setVisibility(View.VISIBLE);
                days.setVisibility(View.GONE);
                everyWeek.setBackgroundResource(R.drawable.round_pastel_yellow);
                everyday.setBackgroundResource(R.drawable.grey_round_button);
                everyMonth.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.everymonth:
                ll.setVisibility(View.GONE);
                days.setVisibility(View.VISIBLE);
                everyMonth.setBackgroundResource(R.drawable.round_pastel_yellow);
                everyday.setBackgroundResource(R.drawable.grey_round_button);
                everyWeek.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.monday:
                monday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.tuesday:
                tuesday.setBackgroundResource(R.drawable.round_pastel_yellow);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.wednesday:
                wednesday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.thursday:
                thursday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.friday:
                friday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.saturday:
                saturday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                sunday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.sunday:
                sunday.setBackgroundResource(R.drawable.round_pastel_yellow);
                tuesday.setBackgroundResource(R.drawable.grey_round_button);
                wednesday.setBackgroundResource(R.drawable.grey_round_button);
                thursday.setBackgroundResource(R.drawable.grey_round_button);
                friday.setBackgroundResource(R.drawable.grey_round_button);
                saturday.setBackgroundResource(R.drawable.grey_round_button);
                monday.setBackgroundResource(R.drawable.grey_round_button);
                break;
            case R.id.one:
                one.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.two:
                two.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.three:
                three.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.four:
                four.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id. five:
                five.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.six:
                six.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.seven:
                seven.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.eight:
                eight.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.nine:
                nine.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.ten:
                ten.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.eleven:
                eleven.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.tweleve:
                twelve.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.thirteen:
                thirteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.fourteen:
                fourteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.fifteen:
                fifteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.sixteen:
                sixteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.seventeen:
                seventeen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.eighteen:
                eighteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.nineteen:
                nineteen.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twenty:
                twenty.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentyone:
                twentyone.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentytwo:
                twentytwo.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentythree:
                twentythree.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentyfour:
                twentyfour.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentyfive:
                twentyfive.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentysix:
                twentysix.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentyseven:
                twentyseven.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                twentyeight.setBackgroundResource(R.drawable.grey_box_button);
                break;
            case R.id.twentyeight:
                twentyeight.setBackgroundResource(R.drawable.pastel_yellow_box_button);
                two.setBackgroundResource(R.drawable.grey_box_button);
                three.setBackgroundResource(R.drawable.grey_box_button);
                four.setBackgroundResource(R.drawable.grey_box_button);
                five.setBackgroundResource(R.drawable.grey_box_button);
                six.setBackgroundResource(R.drawable.grey_box_button);
                seven.setBackgroundResource(R.drawable.grey_box_button);
                eight.setBackgroundResource(R.drawable.grey_box_button);
                nine.setBackgroundResource(R.drawable.grey_box_button);
                ten.setBackgroundResource(R.drawable.grey_box_button);
                eleven.setBackgroundResource(R.drawable.grey_box_button);
                twelve.setBackgroundResource(R.drawable.grey_box_button);
                thirteen.setBackgroundResource(R.drawable.grey_box_button);
                fourteen.setBackgroundResource(R.drawable.grey_box_button);
                fifteen.setBackgroundResource(R.drawable.grey_box_button);
                sixteen.setBackgroundResource(R.drawable.grey_box_button);
                seventeen.setBackgroundResource(R.drawable.grey_box_button);
                eighteen.setBackgroundResource(R.drawable.grey_box_button);
                nineteen.setBackgroundResource(R.drawable.grey_box_button);
                twenty.setBackgroundResource(R.drawable.grey_box_button);
                twentyone.setBackgroundResource(R.drawable.grey_box_button);
                twentytwo.setBackgroundResource(R.drawable.grey_box_button);
                twentythree.setBackgroundResource(R.drawable.grey_box_button);
                twentyfour.setBackgroundResource(R.drawable.grey_box_button);
                twentyfive.setBackgroundResource(R.drawable.grey_box_button);
                twentysix.setBackgroundResource(R.drawable.grey_box_button);
                twentyseven.setBackgroundResource(R.drawable.grey_box_button);
                one.setBackgroundResource(R.drawable.grey_box_button);
                break;
        }
    }
}
